GOOGLE_API_KEY = "AIzaSyDdiSD3Jrqq6qwQ2FmH089RDbDWQ86vrHQ"
GOOGLE_CLOUD_PROJECT = "gen-lang-client-0013992244"
GOOGLE_CLOUD_LOCATION = "us-central1"

CLICKHOUSE_HOST = "j1klx8qg1q.us-east1.gcp.clickhouse.cloud"
CLICKHOUSE_PORT = "8443"
CLICKHOUSE_USER = "default"
CLICKHOUSE_PASSWORD = "DwovCHuz.1XEj"
CLICKHOUSE_SECURE = "true"
CLICKHOUSE_DATABASE = "production_memory"
CLICKHOUSE_ALLOW_WRITE_ACCESS = "true"
